### ISSUE TITLE
Add Bowie Knives ?

### ISSUE THREAD

**Issue by Optllizer** [skittles9823/CS-GO-Knives-for-TTT#3]
I see you added most of the knives but no Bowie knives. will you be adding them anytime soon ?

**Comment by xDShot** [comment]
All knives are already there:

https://github.com/xDShot/csgo_knives_sweps

**Comment by Optllizer** [comment]
No i ment for TTT bc the ones in that pack are t weapons

**Comment by xDShot** [comment]
Mine already have TTT support and it's more up to date and has many bugs fixed and improvements.

**Comment by Optllizer** [comment]
theres no bowie knives 

http://prntscr.com/dyo2y1

http://prntscr.com/dyo31k
